//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FechasCarnets.SVCCAACR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebAuthentication", Namespace="http://schemas.datacontract.org/2004/07/BUSINESS_PARTNER")]
    [System.SerializableAttribute()]
    public partial class WebAuthentication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerAgremiadoResponse", Namespace="http://schemas.datacontract.org/2004/07/BUSINESS_PARTNER")]
    [System.SerializableAttribute()]
    public partial class ObtenerAgremiadoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FechasCarnets.SVCCAACR.BusinessPartner BusinessPartnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FechasCarnets.SVCCAACR.BusinessPartner BusinessPartner {
            get {
                return this.BusinessPartnerField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessPartnerField, value) != true)) {
                    this.BusinessPartnerField = value;
                    this.RaisePropertyChanged("BusinessPartner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessPartner", Namespace="http://schemas.datacontract.org/2004/07/SCG.LS.Service.DataContracts.Types")]
    [System.SerializableAttribute()]
    public partial class BusinessPartner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActiveBPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FechasCarnets.SVCCAACR.BPAddress BPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cellular1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cellular2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfBirthJSONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DeathDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeathDateJSONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EmisionCarnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> IncorporationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncorporationDateJSONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsupToDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotificationMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficeFaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficePhone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfficePhone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionalStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FechasCarnets.SVCCAACR.Properties PropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Surname1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Surname2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalBPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeSuspensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VencimientoCarnetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActiveBP {
            get {
                return this.ActiveBPField;
            }
            set {
                if ((this.ActiveBPField.Equals(value) != true)) {
                    this.ActiveBPField = value;
                    this.RaisePropertyChanged("ActiveBP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FechasCarnets.SVCCAACR.BPAddress BPAddress {
            get {
                return this.BPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BPAddressField, value) != true)) {
                    this.BPAddressField = value;
                    this.RaisePropertyChanged("BPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardCode {
            get {
                return this.CardCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardCodeField, value) != true)) {
                    this.CardCodeField = value;
                    this.RaisePropertyChanged("CardCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellular {
            get {
                return this.CellularField;
            }
            set {
                if ((object.ReferenceEquals(this.CellularField, value) != true)) {
                    this.CellularField = value;
                    this.RaisePropertyChanged("Cellular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellular1 {
            get {
                return this.Cellular1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Cellular1Field, value) != true)) {
                    this.Cellular1Field = value;
                    this.RaisePropertyChanged("Cellular1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cellular2 {
            get {
                return this.Cellular2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Cellular2Field, value) != true)) {
                    this.Cellular2Field = value;
                    this.RaisePropertyChanged("Cellular2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfBirthJSON {
            get {
                return this.DateOfBirthJSONField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfBirthJSONField, value) != true)) {
                    this.DateOfBirthJSONField = value;
                    this.RaisePropertyChanged("DateOfBirthJSON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeathDate {
            get {
                return this.DeathDateField;
            }
            set {
                if ((this.DeathDateField.Equals(value) != true)) {
                    this.DeathDateField = value;
                    this.RaisePropertyChanged("DeathDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeathDateJSON {
            get {
                return this.DeathDateJSONField;
            }
            set {
                if ((object.ReferenceEquals(this.DeathDateJSONField, value) != true)) {
                    this.DeathDateJSONField = value;
                    this.RaisePropertyChanged("DeathDateJSON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EmisionCarnet {
            get {
                return this.EmisionCarnetField;
            }
            set {
                if ((this.EmisionCarnetField.Equals(value) != true)) {
                    this.EmisionCarnetField = value;
                    this.RaisePropertyChanged("EmisionCarnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IncorporationDate {
            get {
                return this.IncorporationDateField;
            }
            set {
                if ((this.IncorporationDateField.Equals(value) != true)) {
                    this.IncorporationDateField = value;
                    this.RaisePropertyChanged("IncorporationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncorporationDateJSON {
            get {
                return this.IncorporationDateJSONField;
            }
            set {
                if ((object.ReferenceEquals(this.IncorporationDateJSONField, value) != true)) {
                    this.IncorporationDateJSONField = value;
                    this.RaisePropertyChanged("IncorporationDateJSON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsupToDate {
            get {
                return this.IsupToDateField;
            }
            set {
                if ((object.ReferenceEquals(this.IsupToDateField, value) != true)) {
                    this.IsupToDateField = value;
                    this.RaisePropertyChanged("IsupToDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationMail {
            get {
                return this.NotificationMailField;
            }
            set {
                if ((object.ReferenceEquals(this.NotificationMailField, value) != true)) {
                    this.NotificationMailField = value;
                    this.RaisePropertyChanged("NotificationMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeFax {
            get {
                return this.OfficeFaxField;
            }
            set {
                if ((object.ReferenceEquals(this.OfficeFaxField, value) != true)) {
                    this.OfficeFaxField = value;
                    this.RaisePropertyChanged("OfficeFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficePhone1 {
            get {
                return this.OfficePhone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.OfficePhone1Field, value) != true)) {
                    this.OfficePhone1Field = value;
                    this.RaisePropertyChanged("OfficePhone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficePhone2 {
            get {
                return this.OfficePhone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.OfficePhone2Field, value) != true)) {
                    this.OfficePhone2Field = value;
                    this.RaisePropertyChanged("OfficePhone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1 {
            get {
                return this.Phone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1Field, value) != true)) {
                    this.Phone1Field = value;
                    this.RaisePropertyChanged("Phone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2 {
            get {
                return this.Phone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2Field, value) != true)) {
                    this.Phone2Field = value;
                    this.RaisePropertyChanged("Phone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfessionalStatus {
            get {
                return this.ProfessionalStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionalStatusField, value) != true)) {
                    this.ProfessionalStatusField = value;
                    this.RaisePropertyChanged("ProfessionalStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FechasCarnets.SVCCAACR.Properties Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicMail {
            get {
                return this.PublicMailField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicMailField, value) != true)) {
                    this.PublicMailField = value;
                    this.RaisePropertyChanged("PublicMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolMail {
            get {
                return this.SchoolMailField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolMailField, value) != true)) {
                    this.SchoolMailField = value;
                    this.RaisePropertyChanged("SchoolMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname1 {
            get {
                return this.Surname1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Surname1Field, value) != true)) {
                    this.Surname1Field = value;
                    this.RaisePropertyChanged("Surname1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname2 {
            get {
                return this.Surname2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Surname2Field, value) != true)) {
                    this.Surname2Field = value;
                    this.RaisePropertyChanged("Surname2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalBP {
            get {
                return this.TotalBPField;
            }
            set {
                if ((this.TotalBPField.Equals(value) != true)) {
                    this.TotalBPField = value;
                    this.RaisePropertyChanged("TotalBP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeSuspension {
            get {
                return this.TypeSuspensionField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeSuspensionField, value) != true)) {
                    this.TypeSuspensionField = value;
                    this.RaisePropertyChanged("TypeSuspension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VencimientoCarnet {
            get {
                return this.VencimientoCarnetField;
            }
            set {
                if ((this.VencimientoCarnetField.Equals(value) != true)) {
                    this.VencimientoCarnetField = value;
                    this.RaisePropertyChanged("VencimientoCarnet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BPAddress", Namespace="http://schemas.datacontract.org/2004/07/SCG.LS.Service.DataContracts.Types")]
    [System.SerializableAttribute()]
    public partial class BPAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FechasCarnets.SVCCAACR.Address[] AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FechasCarnets.SVCCAACR.Address[] Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Properties", Namespace="http://schemas.datacontract.org/2004/07/SCG.LS.Service.DataContracts.Types")]
    [System.SerializableAttribute()]
    public partial class Properties : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QryGroup1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QryGroup64Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QryGroup1 {
            get {
                return this.QryGroup1Field;
            }
            set {
                if ((object.ReferenceEquals(this.QryGroup1Field, value) != true)) {
                    this.QryGroup1Field = value;
                    this.RaisePropertyChanged("QryGroup1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QryGroup64 {
            get {
                return this.QryGroup64Field;
            }
            set {
                if ((object.ReferenceEquals(this.QryGroup64Field, value) != true)) {
                    this.QryGroup64Field = value;
                    this.RaisePropertyChanged("QryGroup64");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/SCG.LS.Service.DataContracts.Types")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExactAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeOfAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExactAddress {
            get {
                return this.ExactAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ExactAddressField, value) != true)) {
                    this.ExactAddressField = value;
                    this.RaisePropertyChanged("ExactAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Site {
            get {
                return this.SiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteField, value) != true)) {
                    this.SiteField = value;
                    this.RaisePropertyChanged("Site");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeOfAddress {
            get {
                return this.TypeOfAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeOfAddressField, value) != true)) {
                    this.TypeOfAddressField = value;
                    this.RaisePropertyChanged("TypeOfAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLawyerResponse", Namespace="http://schemas.datacontract.org/2004/07/BUSINESS_PARTNER")]
    [System.SerializableAttribute()]
    public partial class GetLawyerResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FechasCarnets.SVCCAACR.BusinessPartner[] BusinessPartnersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FechasCarnets.SVCCAACR.BusinessPartner[] BusinessPartners {
            get {
                return this.BusinessPartnersField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessPartnersField, value) != true)) {
                    this.BusinessPartnersField = value;
                    this.RaisePropertyChanged("BusinessPartners");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVCCAACR.IBusinessPartnerService")]
    public interface IBusinessPartnerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/AgremiadoXCarnet", ReplyAction="http://tempuri.org/IBusinessPartnerService/AgremiadoXCarnetResponse")]
        FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse AgremiadoXCarnet(FechasCarnets.SVCCAACR.WebAuthentication authentication, string cardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/AgremiadoXCarnet", ReplyAction="http://tempuri.org/IBusinessPartnerService/AgremiadoXCarnetResponse")]
        System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> AgremiadoXCarnetAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication, string cardCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/AgremiadoXCedula", ReplyAction="http://tempuri.org/IBusinessPartnerService/AgremiadoXCedulaResponse")]
        FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse AgremiadoXCedula(FechasCarnets.SVCCAACR.WebAuthentication authentication, string RFC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/AgremiadoXCedula", ReplyAction="http://tempuri.org/IBusinessPartnerService/AgremiadoXCedulaResponse")]
        System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> AgremiadoXCedulaAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication, string RFC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/TotalBusinessPartners", ReplyAction="http://tempuri.org/IBusinessPartnerService/TotalBusinessPartnersResponse")]
        FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse TotalBusinessPartners(FechasCarnets.SVCCAACR.WebAuthentication authentication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/TotalBusinessPartners", ReplyAction="http://tempuri.org/IBusinessPartnerService/TotalBusinessPartnersResponse")]
        System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> TotalBusinessPartnersAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/ActiveBusinessPartners", ReplyAction="http://tempuri.org/IBusinessPartnerService/ActiveBusinessPartnersResponse")]
        FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse ActiveBusinessPartners(FechasCarnets.SVCCAACR.WebAuthentication authentication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/ActiveBusinessPartners", ReplyAction="http://tempuri.org/IBusinessPartnerService/ActiveBusinessPartnersResponse")]
        System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> ActiveBusinessPartnersAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/ActualizarFechaCarnet", ReplyAction="http://tempuri.org/IBusinessPartnerService/ActualizarFechaCarnetResponse")]
        FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse ActualizarFechaCarnet(FechasCarnets.SVCCAACR.WebAuthentication authentication, string cardCode, System.DateTime emisionCarnet, System.DateTime VencimientoCarnet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/ActualizarFechaCarnet", ReplyAction="http://tempuri.org/IBusinessPartnerService/ActualizarFechaCarnetResponse")]
        System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> ActualizarFechaCarnetAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication, string cardCode, System.DateTime emisionCarnet, System.DateTime VencimientoCarnet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/VaciarTablaTemporal", ReplyAction="http://tempuri.org/IBusinessPartnerService/VaciarTablaTemporalResponse")]
        FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse VaciarTablaTemporal(FechasCarnets.SVCCAACR.WebAuthentication authentication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/VaciarTablaTemporal", ReplyAction="http://tempuri.org/IBusinessPartnerService/VaciarTablaTemporalResponse")]
        System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> VaciarTablaTemporalAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/AgremiadoXNombre", ReplyAction="http://tempuri.org/IBusinessPartnerService/AgremiadoXNombreResponse")]
        FechasCarnets.SVCCAACR.GetLawyerResponse AgremiadoXNombre(FechasCarnets.SVCCAACR.WebAuthentication authentication, string nombre, string ap1, string ap2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessPartnerService/AgremiadoXNombre", ReplyAction="http://tempuri.org/IBusinessPartnerService/AgremiadoXNombreResponse")]
        System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.GetLawyerResponse> AgremiadoXNombreAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication, string nombre, string ap1, string ap2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBusinessPartnerServiceChannel : FechasCarnets.SVCCAACR.IBusinessPartnerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusinessPartnerServiceClient : System.ServiceModel.ClientBase<FechasCarnets.SVCCAACR.IBusinessPartnerService>, FechasCarnets.SVCCAACR.IBusinessPartnerService {
        
        public BusinessPartnerServiceClient() {
        }
        
        public BusinessPartnerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusinessPartnerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessPartnerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusinessPartnerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse AgremiadoXCarnet(FechasCarnets.SVCCAACR.WebAuthentication authentication, string cardCode) {
            return base.Channel.AgremiadoXCarnet(authentication, cardCode);
        }
        
        public System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> AgremiadoXCarnetAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication, string cardCode) {
            return base.Channel.AgremiadoXCarnetAsync(authentication, cardCode);
        }
        
        public FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse AgremiadoXCedula(FechasCarnets.SVCCAACR.WebAuthentication authentication, string RFC) {
            return base.Channel.AgremiadoXCedula(authentication, RFC);
        }
        
        public System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> AgremiadoXCedulaAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication, string RFC) {
            return base.Channel.AgremiadoXCedulaAsync(authentication, RFC);
        }
        
        public FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse TotalBusinessPartners(FechasCarnets.SVCCAACR.WebAuthentication authentication) {
            return base.Channel.TotalBusinessPartners(authentication);
        }
        
        public System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> TotalBusinessPartnersAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication) {
            return base.Channel.TotalBusinessPartnersAsync(authentication);
        }
        
        public FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse ActiveBusinessPartners(FechasCarnets.SVCCAACR.WebAuthentication authentication) {
            return base.Channel.ActiveBusinessPartners(authentication);
        }
        
        public System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> ActiveBusinessPartnersAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication) {
            return base.Channel.ActiveBusinessPartnersAsync(authentication);
        }
        
        public FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse ActualizarFechaCarnet(FechasCarnets.SVCCAACR.WebAuthentication authentication, string cardCode, System.DateTime emisionCarnet, System.DateTime VencimientoCarnet) {
            return base.Channel.ActualizarFechaCarnet(authentication, cardCode, emisionCarnet, VencimientoCarnet);
        }
        
        public System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> ActualizarFechaCarnetAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication, string cardCode, System.DateTime emisionCarnet, System.DateTime VencimientoCarnet) {
            return base.Channel.ActualizarFechaCarnetAsync(authentication, cardCode, emisionCarnet, VencimientoCarnet);
        }
        
        public FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse VaciarTablaTemporal(FechasCarnets.SVCCAACR.WebAuthentication authentication) {
            return base.Channel.VaciarTablaTemporal(authentication);
        }
        
        public System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.ObtenerAgremiadoResponse> VaciarTablaTemporalAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication) {
            return base.Channel.VaciarTablaTemporalAsync(authentication);
        }
        
        public FechasCarnets.SVCCAACR.GetLawyerResponse AgremiadoXNombre(FechasCarnets.SVCCAACR.WebAuthentication authentication, string nombre, string ap1, string ap2) {
            return base.Channel.AgremiadoXNombre(authentication, nombre, ap1, ap2);
        }
        
        public System.Threading.Tasks.Task<FechasCarnets.SVCCAACR.GetLawyerResponse> AgremiadoXNombreAsync(FechasCarnets.SVCCAACR.WebAuthentication authentication, string nombre, string ap1, string ap2) {
            return base.Channel.AgremiadoXNombreAsync(authentication, nombre, ap1, ap2);
        }
    }
}
